apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-autoscaling
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: poc-autoscaling
  template:
    metadata:
      labels:
        app: poc-autoscaling
    spec:
      containers:
        - name: poc-autoscaling
          imagePullPolicy: Always
          image: oseasjs/poc-autoscaling:1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 500m