apiVersion: v1
kind: Service
metadata:
  name: poc-autoscaling-svc
  namespace: default
spec:
  selector:
    app: poc-autoscaling
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
