apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-dep
  namespace: default
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        imagePullPolicy: Always
        image: oseasjs/poc-autoscaling:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi